---
- include: users.yml
- include: pacman.yml
- include: clock.yml
- include: aur.yml
- include: wifi.yml
- include: ssh.yml
- include: shell.yml
- include: gfx.yml
- include: xorg.yml
- include: lightdm.yml
- include: nvim.yml
- include: haskell.yml
- include: xmonad.yml
- include: audio.yml
- include: boot.yml
- include: utils/imgur-screenshot.yml
- include: dev/jdk.yml
- include: dev/gradle.yml
- include: dropbox-fix.yml
- include: cleanup.yml

